allowBuilds:
  '@google/genai': false
  protobufjs: false
  sharp: false
  tree-sitter: false
  tree-sitter-javascript: false
  tree-sitter-typescript: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
